name: CI
on: [ push ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TEST_API_KEY }}
      WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID_GOERLI }}
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pip install --user poetry==1.2.2

      - name: Install poetry dyn version plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Access to execution
        run: chmod +x ${GITHUB_WORKSPACE}/run_tests.sh

      - name: Run tests
        run: ${GITHUB_WORKSPACE}/run_tests.sh
