name: CI
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TEST_API_KEY }}
      WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID_GOERLI }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install poetry
        run: >
          pipx install poetry

      - name: Add poetry to $GITHUB_PATH
        run: >
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Install poetry dyn version plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Access to execution
        run: chmod +x ${GITHUB_WORKSPACE}/run_tests.sh

      - name: Run tests
        run: ${GITHUB_WORKSPACE}/run_tests.sh
